version: 2
jobs:
  build:
    branches:
        only:
          - master
    docker:
      - image: cimg/node:22.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: CI=false npm run build
      - run: npm run deploy