version: 2.1

orbs:
  node: circleci/node@5.1.0


jobs:
  run_tests:
    docker:
      - image circleci/node:10
    steps:
      - checkout
      - run:
        name: Install Dependancies
        command: |
          npm ci
      - run:
        name: Build
        command: |
          npm run build
      - run:
        name: Deploy
        command: |
          npm run deploy
